// <auto-generated />
using System;
using DoctorAppointmentAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DoctorAppointmentAPI.Migrations
{
    [DbContext(typeof(AppoinmentDbContext))]
    partial class AppoinmentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DoctorAppointmentAPI.Models.Chamber", b =>
                {
                    b.Property<int>("ChamberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(300)")
                        .HasMaxLength(300);

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(300)")
                        .HasMaxLength(300);

                    b.HasKey("ChamberId");

                    b.HasIndex("DoctorId");

                    b.ToTable("Chambers");
                });

            modelBuilder.Entity("DoctorAppointmentAPI.Models.DeasisHistory", b =>
                {
                    b.Property<int>("DeasisHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DeasisHistories")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PateintId")
                        .HasColumnType("int");

                    b.HasKey("DeasisHistoryId");

                    b.HasIndex("PateintId");

                    b.ToTable("DeasisHistories");
                });

            modelBuilder.Entity("DoctorAppointmentAPI.Models.Doctor", b =>
                {
                    b.Property<int>("DoctorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AboutDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BMDCNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("GenderId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("SpeacializationId")
                        .HasColumnType("int");

                    b.HasKey("DoctorId");

                    b.HasIndex("GenderId");

                    b.HasIndex("SpeacializationId");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            DoctorId = 3,
                            AboutDetails = "posuere cubilia Curae;",
                            BMDCNumber = "07622222699",
                            Email = "ac@accumsanlaoreetipsum.net",
                            FullName = "Quinn Cantrell",
                            GenderId = 2,
                            PhoneNumber = "",
                            Photo = "in,",
                            SpeacializationId = 46
                        },
                        new
                        {
                            DoctorId = 4,
                            AboutDetails = "eu, ligula. Aenean euismod mauris eu",
                            BMDCNumber = "18856610299",
                            Email = "odio.Nam@Suspendissesagittis.edu",
                            FullName = "Shannon Joyner",
                            GenderId = 2,
                            PhoneNumber = "+8801594995801",
                            Photo = "augue",
                            SpeacializationId = 37
                        },
                        new
                        {
                            DoctorId = 5,
                            AboutDetails = "mattis semper, dui lectus rutrum",
                            BMDCNumber = "26299649199",
                            Email = "nec.euismod@infaucibus.ca",
                            FullName = "Sebastian Le",
                            GenderId = 2,
                            PhoneNumber = "+8801941581791",
                            Photo = "quam.",
                            SpeacializationId = 7
                        },
                        new
                        {
                            DoctorId = 6,
                            AboutDetails = "libero nec ligula consectetuer rhoncus. Nullam velit dui, semper et,",
                            BMDCNumber = "20703595699",
                            Email = "ullamcorper.Duis.at@Maurisblanditenim.com",
                            FullName = "Marvin Rosa",
                            GenderId = 2,
                            PhoneNumber = "+8801561373474",
                            Photo = "cursus",
                            SpeacializationId = 29
                        },
                        new
                        {
                            DoctorId = 7,
                            AboutDetails = "sed pede. Cum sociis natoque penatibus et magnis",
                            BMDCNumber = "49879773799",
                            Email = "Cum.sociis@hymenaeos.org",
                            FullName = "Violet Sosa",
                            GenderId = 1,
                            PhoneNumber = "+8801860521992",
                            Photo = "amet",
                            SpeacializationId = 43
                        },
                        new
                        {
                            DoctorId = 8,
                            AboutDetails = "ac, feugiat non, lobortis quis, pede. Suspendisse",
                            BMDCNumber = "05754018299",
                            Email = "dolor@tellus.co.uk",
                            FullName = "Nathaniel Calderon",
                            GenderId = 1,
                            PhoneNumber = "+8801681003073",
                            Photo = "eleifend",
                            SpeacializationId = 21
                        },
                        new
                        {
                            DoctorId = 9,
                            AboutDetails = "tincidunt, nunc",
                            BMDCNumber = "02230421399",
                            Email = "mi@pharetrafeliseget.edu",
                            FullName = "Rebecca Watson",
                            GenderId = 1,
                            PhoneNumber = "+8801451623005",
                            Photo = "non",
                            SpeacializationId = 2
                        },
                        new
                        {
                            DoctorId = 10,
                            AboutDetails = "sit amet diam eu dolor egestas",
                            BMDCNumber = "57467997499",
                            Email = "egestas.Duis@enim.net",
                            FullName = "Maile Logan",
                            GenderId = 2,
                            PhoneNumber = "",
                            Photo = "Aliquam",
                            SpeacializationId = 29
                        },
                        new
                        {
                            DoctorId = 11,
                            AboutDetails = "in magna. Phasellus dolor elit, pellentesque a, facilisis",
                            BMDCNumber = "57661161899",
                            Email = "Donec.sollicitudin.adipiscing@velitjustonec.com",
                            FullName = "Myles Holt",
                            GenderId = 2,
                            PhoneNumber = "+8801577968365",
                            Photo = "velit.",
                            SpeacializationId = 20
                        },
                        new
                        {
                            DoctorId = 12,
                            AboutDetails = "lectus pede, ultrices a, auctor",
                            BMDCNumber = "02810973599",
                            Email = "ullamcorper.Duis.at@Loremipsumdolor.net",
                            FullName = "Fleur Langley",
                            GenderId = 1,
                            PhoneNumber = "+8801964121766",
                            Photo = "convallis",
                            SpeacializationId = 20
                        },
                        new
                        {
                            DoctorId = 13,
                            AboutDetails = "blandit viverra. Donec tempus, lorem fringilla ornare placerat,",
                            BMDCNumber = "40373236999",
                            Email = "tellus.lorem@velarcuCurabitur.ca",
                            FullName = "Daniel Roach",
                            GenderId = 2,
                            PhoneNumber = "+8801566142650",
                            Photo = "feugiat",
                            SpeacializationId = 18
                        },
                        new
                        {
                            DoctorId = 14,
                            AboutDetails = "dapibus gravida. Aliquam tincidunt, nunc ac mattis ornare, lectus",
                            BMDCNumber = "97275650499",
                            Email = "aliquet@elit.edu",
                            FullName = "Emi Workman",
                            GenderId = 1,
                            PhoneNumber = "+8801390123710",
                            Photo = "purus.",
                            SpeacializationId = 19
                        },
                        new
                        {
                            DoctorId = 15,
                            AboutDetails = "Nullam",
                            BMDCNumber = "02812481799",
                            Email = "tristique.ac.eleifend@Crasloremlorem.ca",
                            FullName = "Leroy Vazquez",
                            GenderId = 2,
                            PhoneNumber = "",
                            Photo = "sit",
                            SpeacializationId = 29
                        },
                        new
                        {
                            DoctorId = 16,
                            AboutDetails = "dapibus id, blandit at, nisi. Cum sociis natoque penatibus",
                            BMDCNumber = "14776587999",
                            Email = "elit.dictum@etmalesuadafames.com",
                            FullName = "Xanthus Webb",
                            GenderId = 1,
                            PhoneNumber = "+8801406012937",
                            Photo = "a",
                            SpeacializationId = 4
                        },
                        new
                        {
                            DoctorId = 17,
                            AboutDetails = "vestibulum massa rutrum",
                            BMDCNumber = "48314646599",
                            Email = "turpis@Vivamus.net",
                            FullName = "Kylynn Hutchinson",
                            GenderId = 2,
                            PhoneNumber = "+8801982973935",
                            Photo = "eget,",
                            SpeacializationId = 45
                        },
                        new
                        {
                            DoctorId = 18,
                            AboutDetails = "justo. Proin non massa non ante bibendum",
                            BMDCNumber = "46293654499",
                            Email = "sit@dictum.ca",
                            FullName = "Vera Sparks",
                            GenderId = 1,
                            PhoneNumber = "+8801658268422",
                            Photo = "Lorem",
                            SpeacializationId = 30
                        },
                        new
                        {
                            DoctorId = 19,
                            AboutDetails = "Etiam",
                            BMDCNumber = "84609695599",
                            Email = "mauris.aliquam@idnunc.edu",
                            FullName = "Aladdin Stout",
                            GenderId = 2,
                            PhoneNumber = "+8801617650206",
                            Photo = "Sed",
                            SpeacializationId = 38
                        },
                        new
                        {
                            DoctorId = 20,
                            AboutDetails = "mattis. Integer eu",
                            BMDCNumber = "14203326599",
                            Email = "mollis@rutrum.ca",
                            FullName = "Samuel Olsen",
                            GenderId = 1,
                            PhoneNumber = "",
                            Photo = "sagittis",
                            SpeacializationId = 48
                        },
                        new
                        {
                            DoctorId = 21,
                            AboutDetails = "aliquet libero. Integer in",
                            BMDCNumber = "39583473099",
                            Email = "sollicitudin.orci@faucibusut.edu",
                            FullName = "Mohammad Diaz",
                            GenderId = 2,
                            PhoneNumber = "+8801924112089",
                            Photo = "lorem",
                            SpeacializationId = 3
                        },
                        new
                        {
                            DoctorId = 22,
                            AboutDetails = "semper. Nam tempor",
                            BMDCNumber = "78298507299",
                            Email = "porttitor.vulputate@et.edu",
                            FullName = "Aaron Parsons",
                            GenderId = 1,
                            PhoneNumber = "+8801850390779",
                            Photo = "sollicitudin",
                            SpeacializationId = 35
                        },
                        new
                        {
                            DoctorId = 23,
                            AboutDetails = "mi, ac mattis velit justo nec ante.",
                            BMDCNumber = "40645623599",
                            Email = "lacus@milacinia.org",
                            FullName = "Finn Bender",
                            GenderId = 2,
                            PhoneNumber = "+8801838913357",
                            Photo = "amet",
                            SpeacializationId = 9
                        },
                        new
                        {
                            DoctorId = 24,
                            AboutDetails = "congue turpis. In condimentum. Donec at arcu.",
                            BMDCNumber = "70461136299",
                            Email = "ligula.eu.enim@sitametconsectetuer.co.uk",
                            FullName = "Chester Richmond",
                            GenderId = 1,
                            PhoneNumber = "+8801521338527",
                            Photo = "convallis,",
                            SpeacializationId = 21
                        },
                        new
                        {
                            DoctorId = 25,
                            AboutDetails = "dolor dolor, tempus non, lacinia",
                            BMDCNumber = "52706338399",
                            Email = "neque@conubianostra.org",
                            FullName = "Xavier Potter",
                            GenderId = 2,
                            PhoneNumber = "+8801388606935",
                            Photo = "nunc.",
                            SpeacializationId = 32
                        },
                        new
                        {
                            DoctorId = 26,
                            AboutDetails = "ullamcorper, nisl arcu iaculis enim, sit amet ornare lectus justo",
                            BMDCNumber = "53985676799",
                            Email = "Vestibulum.ut.eros@nec.ca",
                            FullName = "Karyn Weaver",
                            GenderId = 1,
                            PhoneNumber = "+8801759162601",
                            Photo = "vel,",
                            SpeacializationId = 27
                        },
                        new
                        {
                            DoctorId = 27,
                            AboutDetails = "Sed nec metus facilisis lorem tristique aliquet. Phasellus fermentum",
                            BMDCNumber = "85757459499",
                            Email = "a@eget.co.uk",
                            FullName = "Yoshi Shaw",
                            GenderId = 2,
                            PhoneNumber = "+8801308953168",
                            Photo = "tortor",
                            SpeacializationId = 24
                        },
                        new
                        {
                            DoctorId = 28,
                            AboutDetails = "nulla vulputate dui, nec tempus mauris erat",
                            BMDCNumber = "97327231199",
                            Email = "Suspendisse.tristique.neque@nonbibendum.co.uk",
                            FullName = "Alisa Phillips",
                            GenderId = 2,
                            PhoneNumber = "+8801997064699",
                            Photo = "ridiculus",
                            SpeacializationId = 17
                        },
                        new
                        {
                            DoctorId = 29,
                            AboutDetails = "egestas. Aliquam nec enim. Nunc ut erat.",
                            BMDCNumber = "93652372899",
                            Email = "urna@nisi.org",
                            FullName = "Jerry Jordan",
                            GenderId = 1,
                            PhoneNumber = "",
                            Photo = "Duis",
                            SpeacializationId = 23
                        },
                        new
                        {
                            DoctorId = 30,
                            AboutDetails = "amet diam eu dolor",
                            BMDCNumber = "78977125499",
                            Email = "lorem.eu.metus@lectus.edu",
                            FullName = "Fatima Guy",
                            GenderId = 1,
                            PhoneNumber = "+8801829852224",
                            Photo = "vel,",
                            SpeacializationId = 6
                        },
                        new
                        {
                            DoctorId = 31,
                            AboutDetails = "sagittis lobortis mauris. Suspendisse aliquet molestie tellus. Aenean",
                            BMDCNumber = "14604954699",
                            Email = "feugiat@famesacturpis.co.uk",
                            FullName = "Cheyenne Whitehead",
                            GenderId = 2,
                            PhoneNumber = "+8801343743783",
                            Photo = "elit",
                            SpeacializationId = 27
                        },
                        new
                        {
                            DoctorId = 32,
                            AboutDetails = "adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut",
                            BMDCNumber = "18364251299",
                            Email = "metus@malesuada.edu",
                            FullName = "Zeph Ellis",
                            GenderId = 2,
                            PhoneNumber = "+8801424910323",
                            Photo = "non,",
                            SpeacializationId = 46
                        },
                        new
                        {
                            DoctorId = 33,
                            AboutDetails = "purus. Nullam scelerisque neque sed sem egestas blandit. Nam nulla",
                            BMDCNumber = "19703805599",
                            Email = "montes@elementumpurusaccumsan.net",
                            FullName = "Christopher Hardin",
                            GenderId = 1,
                            PhoneNumber = "+8801897655825",
                            Photo = "a",
                            SpeacializationId = 42
                        },
                        new
                        {
                            DoctorId = 34,
                            AboutDetails = "tellus. Nunc",
                            BMDCNumber = "63262513399",
                            Email = "blandit.Nam@aliquetnecimperdiet.org",
                            FullName = "Willa Ferrell",
                            GenderId = 1,
                            PhoneNumber = "+8801689418780",
                            Photo = "ac",
                            SpeacializationId = 48
                        },
                        new
                        {
                            DoctorId = 35,
                            AboutDetails = "sem.",
                            BMDCNumber = "45303957799",
                            Email = "laoreet.lectus@Quisquevarius.org",
                            FullName = "Keefe Alford",
                            GenderId = 1,
                            PhoneNumber = "+8801539019395",
                            Photo = "nibh.",
                            SpeacializationId = 23
                        },
                        new
                        {
                            DoctorId = 36,
                            AboutDetails = "iaculis enim, sit amet ornare lectus justo eu arcu. Morbi",
                            BMDCNumber = "39250209299",
                            Email = "arcu.Aliquam@Infaucibus.org",
                            FullName = "Forrest Herrera",
                            GenderId = 1,
                            PhoneNumber = "+8801787606178",
                            Photo = "nunc",
                            SpeacializationId = 33
                        },
                        new
                        {
                            DoctorId = 37,
                            AboutDetails = "eros. Proin ultrices. Duis volutpat nunc sit amet metus. Aliquam",
                            BMDCNumber = "04958782699",
                            Email = "nunc@vitaepurus.net",
                            FullName = "Glenna Mcclure",
                            GenderId = 1,
                            PhoneNumber = "+8801566428472",
                            Photo = "commodo",
                            SpeacializationId = 37
                        },
                        new
                        {
                            DoctorId = 38,
                            AboutDetails = "quis, pede. Suspendisse dui. Fusce diam nunc, ullamcorper eu,",
                            BMDCNumber = "37602341999",
                            Email = "Integer.id@gravidanonsollicitudin.net",
                            FullName = "Unity Mccarthy",
                            GenderId = 1,
                            PhoneNumber = "+8801585443078",
                            Photo = "dolor.",
                            SpeacializationId = 18
                        },
                        new
                        {
                            DoctorId = 39,
                            AboutDetails = "blandit",
                            BMDCNumber = "20828049699",
                            Email = "tincidunt@variuset.org",
                            FullName = "Michelle Hardin",
                            GenderId = 1,
                            PhoneNumber = "+8801322337725",
                            Photo = "sem",
                            SpeacializationId = 30
                        },
                        new
                        {
                            DoctorId = 40,
                            AboutDetails = "sit amet",
                            BMDCNumber = "41705657199",
                            Email = "dui@Proinegetodio.net",
                            FullName = "Boris Thompson",
                            GenderId = 1,
                            PhoneNumber = "+8801986818183",
                            Photo = "pede.",
                            SpeacializationId = 15
                        },
                        new
                        {
                            DoctorId = 41,
                            AboutDetails = "dis parturient montes,",
                            BMDCNumber = "83549183499",
                            Email = "magna@malesuada.ca",
                            FullName = "Donovan Richardson",
                            GenderId = 2,
                            PhoneNumber = "+8801712189009",
                            Photo = "arcu.",
                            SpeacializationId = 40
                        },
                        new
                        {
                            DoctorId = 42,
                            AboutDetails = "non massa non ante bibendum ullamcorper. Duis cursus, diam at",
                            BMDCNumber = "22590209199",
                            Email = "amet.luctus@dis.edu",
                            FullName = "Uma Goodwin",
                            GenderId = 2,
                            PhoneNumber = "+8801676269592",
                            Photo = "nec",
                            SpeacializationId = 40
                        },
                        new
                        {
                            DoctorId = 43,
                            AboutDetails = "sed pede nec ante blandit viverra. Donec",
                            BMDCNumber = "52424562799",
                            Email = "Proin@Ut.edu",
                            FullName = "Tad Caldwell",
                            GenderId = 1,
                            PhoneNumber = "+8801697041172",
                            Photo = "rutrum.",
                            SpeacializationId = 29
                        },
                        new
                        {
                            DoctorId = 44,
                            AboutDetails = "tellus sem mollis dui, in",
                            BMDCNumber = "67439536499",
                            Email = "Proin.eget.odio@quam.ca",
                            FullName = "Tana Grant",
                            GenderId = 1,
                            PhoneNumber = "+8801921799330",
                            Photo = "euismod",
                            SpeacializationId = 28
                        },
                        new
                        {
                            DoctorId = 45,
                            AboutDetails = "facilisis lorem",
                            BMDCNumber = "91550839399",
                            Email = "sed@ipsum.co.uk",
                            FullName = "Kuame Guzman",
                            GenderId = 1,
                            PhoneNumber = "+8801448968291",
                            Photo = "est",
                            SpeacializationId = 7
                        },
                        new
                        {
                            DoctorId = 46,
                            AboutDetails = "commodo auctor velit. Aliquam nisl. Nulla eu neque pellentesque massa",
                            BMDCNumber = "31512184899",
                            Email = "posuere.vulputate@ornareegestasligula.edu",
                            FullName = "Sarah Lamb",
                            GenderId = 2,
                            PhoneNumber = "+8801644299924",
                            Photo = "dignissim",
                            SpeacializationId = 36
                        },
                        new
                        {
                            DoctorId = 47,
                            AboutDetails = "enim nec tempus scelerisque, lorem ipsum",
                            BMDCNumber = "58412982999",
                            Email = "consectetuer@utnisi.net",
                            FullName = "Adrienne Branch",
                            GenderId = 1,
                            PhoneNumber = "+8801570990465",
                            Photo = "nulla",
                            SpeacializationId = 16
                        },
                        new
                        {
                            DoctorId = 48,
                            AboutDetails = "lobortis",
                            BMDCNumber = "87311746999",
                            Email = "orci.Phasellus@adui.org",
                            FullName = "Maia Reynolds",
                            GenderId = 1,
                            PhoneNumber = "+8801503657587",
                            Photo = "montes,",
                            SpeacializationId = 3
                        },
                        new
                        {
                            DoctorId = 49,
                            AboutDetails = "tempor diam dictum sapien. Aenean massa.",
                            BMDCNumber = "67514192499",
                            Email = "lacus.Nulla@velitPellentesqueultricies.com",
                            FullName = "Russell Hardy",
                            GenderId = 2,
                            PhoneNumber = "+8801354046141",
                            Photo = "Proin",
                            SpeacializationId = 26
                        },
                        new
                        {
                            DoctorId = 50,
                            AboutDetails = "ornare sagittis felis. Donec tempor, est ac mattis semper, dui",
                            BMDCNumber = "78914336399",
                            Email = "sociis.natoque@sapienAeneanmassa.co.uk",
                            FullName = "Zephr Jarvis",
                            GenderId = 1,
                            PhoneNumber = "+8801646978826",
                            Photo = "eu",
                            SpeacializationId = 41
                        },
                        new
                        {
                            DoctorId = 51,
                            AboutDetails = "sollicitudin a, malesuada",
                            BMDCNumber = "00924577999",
                            Email = "Quisque.ac.libero@senectus.co.uk",
                            FullName = "Leroy Mcintyre",
                            GenderId = 1,
                            PhoneNumber = "+8801425509037",
                            Photo = "consectetuer",
                            SpeacializationId = 15
                        },
                        new
                        {
                            DoctorId = 52,
                            AboutDetails = "mauris.",
                            BMDCNumber = "83214815999",
                            Email = "ligula.Nullam@sed.org",
                            FullName = "Imogene Mooney",
                            GenderId = 1,
                            PhoneNumber = "+8801553851502",
                            Photo = "urna,",
                            SpeacializationId = 9
                        },
                        new
                        {
                            DoctorId = 53,
                            AboutDetails = "risus. Donec egestas. Duis ac arcu.",
                            BMDCNumber = "79833502299",
                            Email = "felis@bibendumDonec.org",
                            FullName = "Chaney Spencer",
                            GenderId = 2,
                            PhoneNumber = "+8801410317127",
                            Photo = "a",
                            SpeacializationId = 17
                        },
                        new
                        {
                            DoctorId = 54,
                            AboutDetails = "vulputate, lacus. Cras interdum. Nunc",
                            BMDCNumber = "08673825099",
                            Email = "sapien.imperdiet@utipsum.ca",
                            FullName = "Xena Thornton",
                            GenderId = 1,
                            PhoneNumber = "+8801478495540",
                            Photo = "Quisque",
                            SpeacializationId = 6
                        },
                        new
                        {
                            DoctorId = 55,
                            AboutDetails = "enim. Suspendisse aliquet, sem ut cursus",
                            BMDCNumber = "44296234599",
                            Email = "Proin.mi@sem.co.uk",
                            FullName = "Ann Klein",
                            GenderId = 1,
                            PhoneNumber = "",
                            Photo = "in",
                            SpeacializationId = 48
                        },
                        new
                        {
                            DoctorId = 56,
                            AboutDetails = "torquent per",
                            BMDCNumber = "61794949799",
                            Email = "consequat.enim@egetmollislectus.edu",
                            FullName = "Lewis Wood",
                            GenderId = 2,
                            PhoneNumber = "",
                            Photo = "Curabitur",
                            SpeacializationId = 35
                        },
                        new
                        {
                            DoctorId = 57,
                            AboutDetails = "viverra. Maecenas iaculis aliquet diam. Sed diam lorem,",
                            BMDCNumber = "72671601999",
                            Email = "sed.pede@mattissemperdui.net",
                            FullName = "Lara Cross",
                            GenderId = 1,
                            PhoneNumber = "+8801495743863",
                            Photo = "erat.",
                            SpeacializationId = 25
                        },
                        new
                        {
                            DoctorId = 58,
                            AboutDetails = "purus gravida sagittis. Duis",
                            BMDCNumber = "74607449099",
                            Email = "lectus@nislsem.edu",
                            FullName = "Quyn Caldwell",
                            GenderId = 1,
                            PhoneNumber = "+8801570969992",
                            Photo = "imperdiet",
                            SpeacializationId = 5
                        },
                        new
                        {
                            DoctorId = 59,
                            AboutDetails = "mauris a nunc. In at pede. Cras vulputate velit",
                            BMDCNumber = "16482322399",
                            Email = "augue@egestas.net",
                            FullName = "Oprah Mathis",
                            GenderId = 2,
                            PhoneNumber = "",
                            Photo = "mauris,",
                            SpeacializationId = 13
                        },
                        new
                        {
                            DoctorId = 60,
                            AboutDetails = "diam at pretium aliquet,",
                            BMDCNumber = "67707292999",
                            Email = "a@Sedidrisus.co.uk",
                            FullName = "Hiroko Graves",
                            GenderId = 1,
                            PhoneNumber = "+8801936530917",
                            Photo = "pharetra",
                            SpeacializationId = 22
                        },
                        new
                        {
                            DoctorId = 61,
                            AboutDetails = "Cras",
                            BMDCNumber = "10731468699",
                            Email = "lectus@ornarelectus.com",
                            FullName = "Phyllis Newton",
                            GenderId = 1,
                            PhoneNumber = "+8801662758102",
                            Photo = "tellus.",
                            SpeacializationId = 3
                        },
                        new
                        {
                            DoctorId = 62,
                            AboutDetails = "rhoncus id, mollis",
                            BMDCNumber = "82387788399",
                            Email = "ut.odio.vel@atvelitCras.edu",
                            FullName = "Olivia Henry",
                            GenderId = 2,
                            PhoneNumber = "",
                            Photo = "a",
                            SpeacializationId = 44
                        },
                        new
                        {
                            DoctorId = 63,
                            AboutDetails = "luctus sit amet, faucibus ut, nulla. Cras",
                            BMDCNumber = "30797890699",
                            Email = "Quisque@nuncInat.ca",
                            FullName = "Vladimir Fox",
                            GenderId = 2,
                            PhoneNumber = "+8801676172440",
                            Photo = "arcu.",
                            SpeacializationId = 36
                        },
                        new
                        {
                            DoctorId = 64,
                            AboutDetails = "justo eu arcu. Morbi sit amet massa. Quisque porttitor eros",
                            BMDCNumber = "63208949399",
                            Email = "ac.turpis.egestas@augueeu.ca",
                            FullName = "Coby Dale",
                            GenderId = 1,
                            PhoneNumber = "+8801816806508",
                            Photo = "nunc",
                            SpeacializationId = 32
                        },
                        new
                        {
                            DoctorId = 65,
                            AboutDetails = "Cras interdum. Nunc",
                            BMDCNumber = "84683078199",
                            Email = "Sed.eu@egetlaoreet.co.uk",
                            FullName = "Natalie Erickson",
                            GenderId = 1,
                            PhoneNumber = "+8801966850065",
                            Photo = "a",
                            SpeacializationId = 21
                        },
                        new
                        {
                            DoctorId = 66,
                            AboutDetails = "Mauris vel turpis. Aliquam adipiscing lobortis risus. In mi pede,",
                            BMDCNumber = "12661555599",
                            Email = "fringilla.mi.lacinia@dui.com",
                            FullName = "Rogan Burke",
                            GenderId = 2,
                            PhoneNumber = "+8801456245720",
                            Photo = "vitae,",
                            SpeacializationId = 13
                        },
                        new
                        {
                            DoctorId = 67,
                            AboutDetails = "feugiat. Lorem ipsum dolor sit amet, consectetuer",
                            BMDCNumber = "42950800499",
                            Email = "primis.in.faucibus@placerategetvenenatis.edu",
                            FullName = "Rae Marsh",
                            GenderId = 1,
                            PhoneNumber = "+8801843474986",
                            Photo = "Aenean",
                            SpeacializationId = 38
                        },
                        new
                        {
                            DoctorId = 68,
                            AboutDetails = "Phasellus dapibus quam quis diam. Pellentesque habitant morbi",
                            BMDCNumber = "82780205499",
                            Email = "nunc@lectusCumsociis.com",
                            FullName = "Dolan Wall",
                            GenderId = 1,
                            PhoneNumber = "",
                            Photo = "pharetra",
                            SpeacializationId = 15
                        },
                        new
                        {
                            DoctorId = 69,
                            AboutDetails = "ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam auctor,",
                            BMDCNumber = "92464257299",
                            Email = "Nullam.vitae.diam@elitfermentum.co.uk",
                            FullName = "Hamish Atkins",
                            GenderId = 2,
                            PhoneNumber = "+8801852610935",
                            Photo = "urna.",
                            SpeacializationId = 5
                        },
                        new
                        {
                            DoctorId = 70,
                            AboutDetails = "molestie tellus. Aenean egestas hendrerit neque. In ornare sagittis felis.",
                            BMDCNumber = "70931536599",
                            Email = "dictum.mi.ac@felisadipiscingfringilla.edu",
                            FullName = "Lael Barnes",
                            GenderId = 1,
                            PhoneNumber = "+8801945371555",
                            Photo = "aliquet",
                            SpeacializationId = 20
                        },
                        new
                        {
                            DoctorId = 71,
                            AboutDetails = "nunc ac",
                            BMDCNumber = "45954320799",
                            Email = "nisi@tinciduntaliquamarcu.co.uk",
                            FullName = "Merritt Wilson",
                            GenderId = 2,
                            PhoneNumber = "",
                            Photo = "hendrerit",
                            SpeacializationId = 1
                        },
                        new
                        {
                            DoctorId = 72,
                            AboutDetails = "purus. Nullam scelerisque",
                            BMDCNumber = "07841749499",
                            Email = "tristique.senectus@Proin.co.uk",
                            FullName = "Dustin Hinton",
                            GenderId = 2,
                            PhoneNumber = "",
                            Photo = "Donec",
                            SpeacializationId = 39
                        },
                        new
                        {
                            DoctorId = 73,
                            AboutDetails = "hendrerit. Donec porttitor tellus non magna. Nam ligula",
                            BMDCNumber = "90408368499",
                            Email = "euismod.enim@egetdictum.com",
                            FullName = "Georgia Flynn",
                            GenderId = 2,
                            PhoneNumber = "",
                            Photo = "mauris,",
                            SpeacializationId = 24
                        },
                        new
                        {
                            DoctorId = 74,
                            AboutDetails = "quis accumsan convallis, ante lectus convallis est,",
                            BMDCNumber = "94644364899",
                            Email = "odio.vel@pretiumnequeMorbi.co.uk",
                            FullName = "Abel Bates",
                            GenderId = 2,
                            PhoneNumber = "+8801389451326",
                            Photo = "est",
                            SpeacializationId = 45
                        },
                        new
                        {
                            DoctorId = 75,
                            AboutDetails = "netus",
                            BMDCNumber = "27479547099",
                            Email = "nonummy.ipsum.non@egestasurnajusto.co.uk",
                            FullName = "Palmer Bruce",
                            GenderId = 1,
                            PhoneNumber = "",
                            Photo = "tincidunt",
                            SpeacializationId = 41
                        },
                        new
                        {
                            DoctorId = 76,
                            AboutDetails = "est. Nunc ullamcorper, velit in aliquet lobortis, nisi",
                            BMDCNumber = "38491621699",
                            Email = "Duis@CuraeDonec.edu",
                            FullName = "Lee Silva",
                            GenderId = 1,
                            PhoneNumber = "+8801432755557",
                            Photo = "sed",
                            SpeacializationId = 24
                        },
                        new
                        {
                            DoctorId = 77,
                            AboutDetails = "Phasellus dapibus",
                            BMDCNumber = "74461762499",
                            Email = "pellentesque.a.facilisis@magna.edu",
                            FullName = "September Brock",
                            GenderId = 2,
                            PhoneNumber = "",
                            Photo = "vitae",
                            SpeacializationId = 22
                        },
                        new
                        {
                            DoctorId = 78,
                            AboutDetails = "sem semper erat,",
                            BMDCNumber = "78766425699",
                            Email = "turpis.vitae@Etiam.edu",
                            FullName = "Boris Carson",
                            GenderId = 1,
                            PhoneNumber = "+8801742924522",
                            Photo = "tempus",
                            SpeacializationId = 24
                        },
                        new
                        {
                            DoctorId = 79,
                            AboutDetails = "feugiat non, lobortis quis, pede. Suspendisse dui.",
                            BMDCNumber = "24883532099",
                            Email = "at.risus@habitantmorbi.com",
                            FullName = "Slade Lawson",
                            GenderId = 1,
                            PhoneNumber = "+8801989236874",
                            Photo = "lorem",
                            SpeacializationId = 29
                        },
                        new
                        {
                            DoctorId = 80,
                            AboutDetails = "dolor vitae dolor. Donec fringilla. Donec feugiat",
                            BMDCNumber = "30696950099",
                            Email = "at.augue.id@tristiquepellentesquetellus.edu",
                            FullName = "Hop Fischer",
                            GenderId = 2,
                            PhoneNumber = "+8801625777110",
                            Photo = "sit",
                            SpeacializationId = 6
                        },
                        new
                        {
                            DoctorId = 81,
                            AboutDetails = "ligula. Aenean gravida nunc sed pede.",
                            BMDCNumber = "83838653299",
                            Email = "Aenean.egestas.hendrerit@augueeu.edu",
                            FullName = "Akeem Hopper",
                            GenderId = 1,
                            PhoneNumber = "+8801981602387",
                            Photo = "adipiscing",
                            SpeacializationId = 14
                        },
                        new
                        {
                            DoctorId = 82,
                            AboutDetails = "euismod mauris eu elit. Nulla facilisi. Sed neque. Sed eget",
                            BMDCNumber = "22463337699",
                            Email = "arcu.Vestibulum@Nullasemper.org",
                            FullName = "Hillary Adkins",
                            GenderId = 2,
                            PhoneNumber = "+8801909355544",
                            Photo = "litora",
                            SpeacializationId = 12
                        },
                        new
                        {
                            DoctorId = 83,
                            AboutDetails = "sem semper erat, in consectetuer ipsum",
                            BMDCNumber = "18310651399",
                            Email = "magna.Lorem.ipsum@sedturpisnec.edu",
                            FullName = "Cullen Harper",
                            GenderId = 1,
                            PhoneNumber = "+8801624993599",
                            Photo = "eu,",
                            SpeacializationId = 5
                        },
                        new
                        {
                            DoctorId = 84,
                            AboutDetails = "non, lobortis quis, pede. Suspendisse dui. Fusce",
                            BMDCNumber = "93840782599",
                            Email = "tellus.non.magna@quismassa.co.uk",
                            FullName = "Porter Roy",
                            GenderId = 2,
                            PhoneNumber = "+8801729388454",
                            Photo = "Donec",
                            SpeacializationId = 41
                        },
                        new
                        {
                            DoctorId = 85,
                            AboutDetails = "ante. Maecenas mi felis, adipiscing fringilla, porttitor vulputate,",
                            BMDCNumber = "33637396599",
                            Email = "Praesent.interdum.ligula@Nulla.net",
                            FullName = "Jessamine Goodwin",
                            GenderId = 2,
                            PhoneNumber = "",
                            Photo = "mauris",
                            SpeacializationId = 34
                        },
                        new
                        {
                            DoctorId = 86,
                            AboutDetails = "libero et",
                            BMDCNumber = "75973664699",
                            Email = "Nam.ligula@cursus.ca",
                            FullName = "Kirk Erickson",
                            GenderId = 2,
                            PhoneNumber = "+8801525832013",
                            Photo = "montes,",
                            SpeacializationId = 1
                        },
                        new
                        {
                            DoctorId = 87,
                            AboutDetails = "mauris",
                            BMDCNumber = "46242890399",
                            Email = "id.ante@orci.edu",
                            FullName = "Burke Salazar",
                            GenderId = 1,
                            PhoneNumber = "+8801841534593",
                            Photo = "Cras",
                            SpeacializationId = 21
                        },
                        new
                        {
                            DoctorId = 88,
                            AboutDetails = "ultricies ornare, elit",
                            BMDCNumber = "35733456599",
                            Email = "velit@ultrices.com",
                            FullName = "Jolie Spence",
                            GenderId = 2,
                            PhoneNumber = "+8801756206394",
                            Photo = "sed,",
                            SpeacializationId = 15
                        },
                        new
                        {
                            DoctorId = 89,
                            AboutDetails = "feugiat placerat velit. Quisque varius. Nam porttitor scelerisque neque.",
                            BMDCNumber = "57875036799",
                            Email = "ac@Phasellus.ca",
                            FullName = "Kennedy Britt",
                            GenderId = 2,
                            PhoneNumber = "+8801355741542",
                            Photo = "Praesent",
                            SpeacializationId = 34
                        },
                        new
                        {
                            DoctorId = 90,
                            AboutDetails = "diam vel",
                            BMDCNumber = "79665271799",
                            Email = "pede.ac.urna@Mauris.co.uk",
                            FullName = "Benjamin Dejesus",
                            GenderId = 2,
                            PhoneNumber = "+8801307588639",
                            Photo = "Fusce",
                            SpeacializationId = 42
                        },
                        new
                        {
                            DoctorId = 91,
                            AboutDetails = "Aliquam",
                            BMDCNumber = "19859094099",
                            Email = "commodo.auctor@estacfacilisis.co.uk",
                            FullName = "Dorothy Berger",
                            GenderId = 1,
                            PhoneNumber = "+8801595147681",
                            Photo = "Sed",
                            SpeacializationId = 34
                        },
                        new
                        {
                            DoctorId = 92,
                            AboutDetails = "posuere vulputate, lacus. Cras interdum. Nunc",
                            BMDCNumber = "35942203399",
                            Email = "vulputate@vulputatenisi.net",
                            FullName = "Justin Walls",
                            GenderId = 1,
                            PhoneNumber = "+8801474973712",
                            Photo = "mauris",
                            SpeacializationId = 44
                        },
                        new
                        {
                            DoctorId = 93,
                            AboutDetails = "erat. Etiam vestibulum massa rutrum magna. Cras convallis convallis dolor.",
                            BMDCNumber = "91264681199",
                            Email = "fermentum.vel@luctuslobortis.edu",
                            FullName = "Neil Fowler",
                            GenderId = 2,
                            PhoneNumber = "+8801883147653",
                            Photo = "nulla",
                            SpeacializationId = 6
                        },
                        new
                        {
                            DoctorId = 94,
                            AboutDetails = "ipsum ac mi eleifend egestas.",
                            BMDCNumber = "75527336399",
                            Email = "dui.Fusce@elementum.org",
                            FullName = "Lars Vargas",
                            GenderId = 2,
                            PhoneNumber = "+8801463346472",
                            Photo = "arcu.",
                            SpeacializationId = 3
                        },
                        new
                        {
                            DoctorId = 95,
                            AboutDetails = "quis,",
                            BMDCNumber = "70817478799",
                            Email = "risus.odio@risusMorbimetus.org",
                            FullName = "Abra Hamilton",
                            GenderId = 2,
                            PhoneNumber = "+8801401235934",
                            Photo = "non,",
                            SpeacializationId = 17
                        },
                        new
                        {
                            DoctorId = 96,
                            AboutDetails = "mollis. Duis sit",
                            BMDCNumber = "83553417499",
                            Email = "non@eros.edu",
                            FullName = "Donna Riley",
                            GenderId = 2,
                            PhoneNumber = "",
                            Photo = "sagittis",
                            SpeacializationId = 41
                        },
                        new
                        {
                            DoctorId = 97,
                            AboutDetails = "egestas blandit. Nam nulla magna, malesuada vel, convallis in, cursus",
                            BMDCNumber = "53734856699",
                            Email = "a.enim.Suspendisse@VivamusnisiMauris.edu",
                            FullName = "Dean Berry",
                            GenderId = 1,
                            PhoneNumber = "",
                            Photo = "eget,",
                            SpeacializationId = 15
                        },
                        new
                        {
                            DoctorId = 98,
                            AboutDetails = "sit amet orci.",
                            BMDCNumber = "04594595199",
                            Email = "leo@vestibulumloremsit.co.uk",
                            FullName = "Britanni Sparks",
                            GenderId = 1,
                            PhoneNumber = "+8801304904215",
                            Photo = "consectetuer",
                            SpeacializationId = 42
                        },
                        new
                        {
                            DoctorId = 99,
                            AboutDetails = "justo nec ante. Maecenas",
                            BMDCNumber = "09726817399",
                            Email = "Nam.porttitor.scelerisque@estvitae.ca",
                            FullName = "Quamar Burton",
                            GenderId = 1,
                            PhoneNumber = "+8801391699724",
                            Photo = "amet",
                            SpeacializationId = 14
                        },
                        new
                        {
                            DoctorId = 100,
                            AboutDetails = "sit amet ultricies sem",
                            BMDCNumber = "13695276299",
                            Email = "rutrum.magna@dolorsit.org",
                            FullName = "Ivan Alvarado",
                            GenderId = 2,
                            PhoneNumber = "+8801806688924",
                            Photo = "sapien.",
                            SpeacializationId = 40
                        });
                });

            modelBuilder.Entity("DoctorAppointmentAPI.Models.Gender", b =>
                {
                    b.Property<int>("GenderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GenderName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GenderId");

                    b.ToTable("Genders");

                    b.HasData(
                        new
                        {
                            GenderId = 1,
                            GenderName = "Male"
                        },
                        new
                        {
                            GenderId = 2,
                            GenderName = "Female"
                        });
                });

            modelBuilder.Entity("DoctorAppointmentAPI.Models.Pateint", b =>
                {
                    b.Property<int>("PateintId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("GenderId")
                        .HasColumnType("int");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("PateintId");

                    b.HasIndex("GenderId");

                    b.ToTable("Pateints");

                    b.HasData(
                        new
                        {
                            PateintId = 1,
                            Age = 25,
                            GenderId = 1,
                            MobileNumber = "01758091506",
                            Name = "Mahfozur Rahman"
                        },
                        new
                        {
                            PateintId = 2,
                            Age = 42,
                            GenderId = 1,
                            MobileNumber = "01745632145",
                            Name = "Wahidur Rahman"
                        },
                        new
                        {
                            PateintId = 3,
                            Age = 27,
                            GenderId = 1,
                            MobileNumber = "01652147896",
                            Name = "Masum Billah"
                        },
                        new
                        {
                            PateintId = 4,
                            Age = 25,
                            GenderId = 2,
                            MobileNumber = "01758091506",
                            Name = "Shanta Jahan"
                        },
                        new
                        {
                            PateintId = 5,
                            Age = 21,
                            GenderId = 2,
                            MobileNumber = "05616515651",
                            Name = "Moushumi Akter"
                        },
                        new
                        {
                            PateintId = 6,
                            Age = 23,
                            GenderId = 1,
                            MobileNumber = "464864864685",
                            Name = "Wali Ullah"
                        },
                        new
                        {
                            PateintId = 7,
                            Age = 22,
                            GenderId = 1,
                            MobileNumber = "5664666155",
                            Name = "Sadik Rahman"
                        },
                        new
                        {
                            PateintId = 8,
                            Age = 24,
                            GenderId = 2,
                            MobileNumber = "011565668466",
                            Name = "Happy Rose"
                        },
                        new
                        {
                            PateintId = 9,
                            Age = 35,
                            GenderId = 2,
                            MobileNumber = "01475656526",
                            Name = "Rita Sheikh"
                        },
                        new
                        {
                            PateintId = 10,
                            Age = 30,
                            GenderId = 1,
                            MobileNumber = "019215666245",
                            Name = "Selim Sheikh"
                        },
                        new
                        {
                            PateintId = 11,
                            Age = 25,
                            GenderId = 2,
                            MobileNumber = "01754152632",
                            Name = "Aleya Ferdaus"
                        });
                });

            modelBuilder.Entity("DoctorAppointmentAPI.Models.RoasterOfDoctor", b =>
                {
                    b.Property<int>("RoasterOfDoctorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ChamberId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("EstimatedPateintNumber")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("TimeEnd")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("TimeStart")
                        .HasColumnType("time");

                    b.HasKey("RoasterOfDoctorId");

                    b.HasIndex("ChamberId");

                    b.HasIndex("DoctorId");

                    b.ToTable("RoasterOfDoctors");
                });

            modelBuilder.Entity("DoctorAppointmentAPI.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RoleName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("DoctorAppointmentAPI.Models.Serial", b =>
                {
                    b.Property<int>("SerialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PateintId")
                        .HasColumnType("int");

                    b.Property<int>("RoasterOfDoctorId")
                        .HasColumnType("int");

                    b.Property<int>("SerialNumber")
                        .HasColumnType("int");

                    b.HasKey("SerialId");

                    b.HasIndex("PateintId");

                    b.HasIndex("RoasterOfDoctorId");

                    b.ToTable("Serials");
                });

            modelBuilder.Entity("DoctorAppointmentAPI.Models.Speacialization", b =>
                {
                    b.Property<int>("SpeacializationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SpeacializationDepartment")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("SpeacializationId");

                    b.ToTable("Speacializations");

                    b.HasData(
                        new
                        {
                            SpeacializationId = 1,
                            SpeacializationDepartment = "Aerospace Medicine"
                        },
                        new
                        {
                            SpeacializationId = 2,
                            SpeacializationDepartment = "Bariatric Surgery "
                        },
                        new
                        {
                            SpeacializationId = 3,
                            SpeacializationDepartment = "Cardiology - Interventional "
                        },
                        new
                        {
                            SpeacializationId = 4,
                            SpeacializationDepartment = "Cardiology - Non Interventional "
                        },
                        new
                        {
                            SpeacializationId = 5,
                            SpeacializationDepartment = "Cardiothoracic And Vascular Surgery "
                        },
                        new
                        {
                            SpeacializationId = 6,
                            SpeacializationDepartment = "Centre For Spinal Diseases "
                        },
                        new
                        {
                            SpeacializationId = 7,
                            SpeacializationDepartment = "Clinical Haematology And BMT "
                        },
                        new
                        {
                            SpeacializationId = 8,
                            SpeacializationDepartment = "Corneal Transplant "
                        },
                        new
                        {
                            SpeacializationId = 9,
                            SpeacializationDepartment = "Critical Care Medicine "
                        },
                        new
                        {
                            SpeacializationId = 10,
                            SpeacializationDepartment = "Dermatology And Cosmetology "
                        },
                        new
                        {
                            SpeacializationId = 11,
                            SpeacializationDepartment = "Ear Nose Throat Head And Neck Surgery "
                        },
                        new
                        {
                            SpeacializationId = 12,
                            SpeacializationDepartment = "Emergency Medicine "
                        },
                        new
                        {
                            SpeacializationId = 13,
                            SpeacializationDepartment = "Endocrinology "
                        },
                        new
                        {
                            SpeacializationId = 14,
                            SpeacializationDepartment = "General Surgery "
                        },
                        new
                        {
                            SpeacializationId = 15,
                            SpeacializationDepartment = "Infectious Diseases "
                        },
                        new
                        {
                            SpeacializationId = 16,
                            SpeacializationDepartment = "Internal Medicine "
                        },
                        new
                        {
                            SpeacializationId = 17,
                            SpeacializationDepartment = "In-Vitro Fertilisation (IVF) "
                        },
                        new
                        {
                            SpeacializationId = 18,
                            SpeacializationDepartment = "Laboratory Medicine "
                        },
                        new
                        {
                            SpeacializationId = 19,
                            SpeacializationDepartment = "Liver Transplant & Hepatic Surgery "
                        },
                        new
                        {
                            SpeacializationId = 20,
                            SpeacializationDepartment = "Maxillofacial Surgery "
                        },
                        new
                        {
                            SpeacializationId = 21,
                            SpeacializationDepartment = "Medical Gastroenterology "
                        },
                        new
                        {
                            SpeacializationId = 22,
                            SpeacializationDepartment = "Medical Oncology & Clinical Hematology "
                        },
                        new
                        {
                            SpeacializationId = 23,
                            SpeacializationDepartment = "Medical Oncology "
                        },
                        new
                        {
                            SpeacializationId = 24,
                            SpeacializationDepartment = "Minimally Invasive Gynecology "
                        },
                        new
                        {
                            SpeacializationId = 25,
                            SpeacializationDepartment = "Neonatology "
                        },
                        new
                        {
                            SpeacializationId = 26,
                            SpeacializationDepartment = "Nephrology "
                        },
                        new
                        {
                            SpeacializationId = 27,
                            SpeacializationDepartment = "Neuro Modulation "
                        },
                        new
                        {
                            SpeacializationId = 28,
                            SpeacializationDepartment = "Nutrition & Dietetics "
                        },
                        new
                        {
                            SpeacializationId = 29,
                            SpeacializationDepartment = "Neurology "
                        },
                        new
                        {
                            SpeacializationId = 30,
                            SpeacializationDepartment = "Neurosurgery "
                        },
                        new
                        {
                            SpeacializationId = 31,
                            SpeacializationDepartment = "Obstetrics And Gynecology "
                        },
                        new
                        {
                            SpeacializationId = 32,
                            SpeacializationDepartment = "Ophthalmology "
                        },
                        new
                        {
                            SpeacializationId = 33,
                            SpeacializationDepartment = "Orthopedics & Joint Replacement "
                        },
                        new
                        {
                            SpeacializationId = 34,
                            SpeacializationDepartment = "Pain Management "
                        },
                        new
                        {
                            SpeacializationId = 35,
                            SpeacializationDepartment = "Pediatric Surgery "
                        },
                        new
                        {
                            SpeacializationId = 36,
                            SpeacializationDepartment = "Physiotherapy "
                        },
                        new
                        {
                            SpeacializationId = 37,
                            SpeacializationDepartment = "Plastic Surgery "
                        },
                        new
                        {
                            SpeacializationId = 38,
                            SpeacializationDepartment = "Psychiatry "
                        },
                        new
                        {
                            SpeacializationId = 39,
                            SpeacializationDepartment = "Pulmonology "
                        },
                        new
                        {
                            SpeacializationId = 40,
                            SpeacializationDepartment = "Renal Transplant "
                        },
                        new
                        {
                            SpeacializationId = 41,
                            SpeacializationDepartment = "Reproductive Medicine & IVF "
                        },
                        new
                        {
                            SpeacializationId = 42,
                            SpeacializationDepartment = "Rheumatology "
                        },
                        new
                        {
                            SpeacializationId = 43,
                            SpeacializationDepartment = "Robotic Surgery "
                        },
                        new
                        {
                            SpeacializationId = 44,
                            SpeacializationDepartment = "Surgical Gastroenterology "
                        },
                        new
                        {
                            SpeacializationId = 45,
                            SpeacializationDepartment = "Surgical Oncology "
                        },
                        new
                        {
                            SpeacializationId = 46,
                            SpeacializationDepartment = "Urology "
                        },
                        new
                        {
                            SpeacializationId = 47,
                            SpeacializationDepartment = "Vascular and endovascular surgery "
                        },
                        new
                        {
                            SpeacializationId = 48,
                            SpeacializationDepartment = "Anaesthesia"
                        });
                });

            modelBuilder.Entity("DoctorAppointmentAPI.Models.tblUser", b =>
                {
                    b.Property<int>("tblUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("tblUserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DoctorAppointmentAPI.Models.Chamber", b =>
                {
                    b.HasOne("DoctorAppointmentAPI.Models.Doctor", "Doctor")
                        .WithMany("Chambers")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DoctorAppointmentAPI.Models.DeasisHistory", b =>
                {
                    b.HasOne("DoctorAppointmentAPI.Models.Pateint", "Pateint")
                        .WithMany("DeasisHistories")
                        .HasForeignKey("PateintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DoctorAppointmentAPI.Models.Doctor", b =>
                {
                    b.HasOne("DoctorAppointmentAPI.Models.Gender", "Gender")
                        .WithMany("Doctors")
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoctorAppointmentAPI.Models.Speacialization", "Speacialization")
                        .WithMany("Doctors")
                        .HasForeignKey("SpeacializationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DoctorAppointmentAPI.Models.Pateint", b =>
                {
                    b.HasOne("DoctorAppointmentAPI.Models.Gender", "Gender")
                        .WithMany("Pateints")
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DoctorAppointmentAPI.Models.RoasterOfDoctor", b =>
                {
                    b.HasOne("DoctorAppointmentAPI.Models.Chamber", "Chamber")
                        .WithMany("RoasterOfDoctors")
                        .HasForeignKey("ChamberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoctorAppointmentAPI.Models.Doctor", "Doctor")
                        .WithMany("RoasterOfDoctors")
                        .HasForeignKey("DoctorId");
                });

            modelBuilder.Entity("DoctorAppointmentAPI.Models.Serial", b =>
                {
                    b.HasOne("DoctorAppointmentAPI.Models.Pateint", "Pateint")
                        .WithMany("Serials")
                        .HasForeignKey("PateintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoctorAppointmentAPI.Models.RoasterOfDoctor", "RoasterOfDoctor")
                        .WithMany("Serials")
                        .HasForeignKey("RoasterOfDoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DoctorAppointmentAPI.Models.tblUser", b =>
                {
                    b.HasOne("DoctorAppointmentAPI.Models.Role", "Roles")
                        .WithMany("tblUsers")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
